# Generated by Django 6.0.5 on 2026-05-31 15:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_recipe_servings_alter_recipe_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_ingredient_name_ci",
            ),
        ),
    ]
