# Generated by Django 6.0.5 on 2026-05-31 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.realweek')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week', 'weekday', 'meal_type'), name='unique_realweek_slot')],
            },
        ),
        migrations.CreateModel(
            name='TemplateMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20)),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.weektemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template', 'weekday', 'meal_type'), name='unique_template_slot')],
            },
        ),
    ]
