# Generated by Django 6.0.5 on 2026-05-31 18:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WeekTemplate",
            new_name="TemplateWeek",
        ),
    ]
